
################################################################################
# Universal adjustable settings

ModelGen = 6

ObjFunNames = c("PeakSWE_RMSE","Total_NSE","LowBase_LogNSE","HighBase_LogNSE","WaterYield_RMSE","PeakFlow_RMSE")
ObjFunLongNames = c("Peak SWE","Total NSE","Low-Baseflow Log NSE","High-Baseflow Log NSE","Yearly Water Yield","95th-Percentile Peak Flows")
ObjFunLongNamesTight = c("Peak\nSWE","Total\nNSE","Low-Baseflow\nLog NSE","High-Baseflow\nLog NSE","Yearly\nWater Yield","95th-Percentile\nPeak Flows")
nObjFuns = length(ObjFunNames)

ParamNames = c("SOILD","SLHC","POROSITY","EXPDEC","MINRES","SNOWTEMP","ALBMELTRATE")
ParamLongNames = c("Soil Depth","Hydraulic Conductivity","Porosity","Ksat Exponential Decrease","Minimum Stomatal Resistance","Snow Temperature Threshold","Melt-Season Albedo Decay Rate")
ParamLongNamesTight = c("Soil\nDepth","Hydraulic\nConductivity","Porosity","Ksat Exp.\nDecrease","Min. Stomatal\nResistance","Snow Temp.\nThreshold","Melt-Season\nAlbedo Decay")
nParams = length(ParamNames)

BasinNames = c("Truckee","Yuba")

# Extra information to visualize particular objective functions
SnowYears = 2011:2016
StreamYears = 2012:2017
nSnowYears = length(SnowYears)
nStreamYears = length(StreamYears)
ModelInterval = 3 # hours

ResultsDir = "Results/" # Where the files created by DHSVM are stored
ReferenceDir = "ReferenceData/" # Where the files used as ground-truth are stored

dir = "C:/Users/board/Documents/DHSVM/DHSVM-PNNL-master/Calibrate_MOBOhydro/"
setwd(dir)

################################################################################
# Calibration data

GaugeIDs = c(11413000)
GaugeNames = c("North Yuba River")
CatchmentAreas = c(250) # Areas in mi^2 from USGS

# Read dataframe of streamflow data generated by ProcessStreamflowForDHSVM.R
ReferenceStreamflow = read.csv(paste0(ReferenceDir,"USGS_StreamflowData.csv"))[,-1]
head(ReferenceStreamflow)

# Choose which parameter sets are of interest
VisualizeParameters = c(195,270,276)

AllDates = c()
AllStreamflowVals = c()
AllValueTypes = c()
AllGaugeIDs = c()

# Loop over each parameter set and calculate the objective function value
for (i in VisualizeParameters){
  # Loop over modeled watersheds
  for (bsn in 1:length(BasinNames)){
    # Read the streamflow data output by DHSVM (drop first line that is date-only)
    DHSVMheader = read.table(paste0(ResultsDir,"Params",i,"_",BasinNames[bsn],"/Streamflow.Only"), nrows=1)
    DHSVMstreamflow = read.table(paste0(ResultsDir,"Params",i,"_",BasinNames[bsn],"/Streamflow.Only"), skip=2)
    names(DHSVMstreamflow) = DHSVMheader
    DHSVMstreamflow$DATE = as.Date(DHSVMstreamflow$DATE, format="%m.%d.%Y") # Convert to day only
    
    # Loop over each gauge
    for (gauge in 1:length(GaugeIDs)){
      
      # Only proceed if this gauge is in the current watershed
      if (paste0("Gauge_",GaugeIDs[gauge]) %in% DHSVMheader){
        
        # Reset the vector containing modeled values to be compared with reference data
        DHSVMvals = c()
        # Parse the corresponding reference values into a vector
        ReferenceVals = ReferenceStreamflow[,paste0("Gauge_",GaugeIDs[gauge])]
        
        # Aggregate DHSVM output from m^3/timestep to m^3/s as a daily average for the current gauge
        for (day in 1:length(ReferenceStreamflow$Date)){
          Ptrs = which(DHSVMstreamflow$DATE == ReferenceStreamflow$Date[day])
          DailyQ = sum(DHSVMstreamflow[,paste0("Gauge_",GaugeIDs[gauge])][Ptrs]) / (24*60*60) # m^3/timestep --> m^3/s
          
          # Append to hydrograph for NSE
          DHSVMvals = c(DHSVMvals, DailyQ)
          
        } # End of daily gauge aggregation loop
        
        # Convert m^3/s to mm/d
        DHSVMvals = 1000 * DHSVMvals * (60*60*24) / (CatchmentAreas[gauge] * 2.58999 * 1000^2)
        ReferenceVals = 1000 * ReferenceVals * (60*60*24) / (CatchmentAreas[gauge] * 2.58999 * 1000^2)
        
        if (i==VisualizeParameters[1]){
          AllDates = c(AllDates,ReferenceStreamflow$Date)
          AllStreamflowVals = c(AllStreamflowVals,ReferenceVals)
          AllValueTypes = c(AllValueTypes,rep("Measured",length(ReferenceVals)))
          AllGaugeIDs = c(AllGaugeIDs,rep(GaugeIDs[gauge],length(ReferenceVals)))
        }
        
        AllDates = c(AllDates,ReferenceStreamflow$Date)
        AllStreamflowVals = c(AllStreamflowVals,DHSVMvals)
        AllValueTypes = c(AllValueTypes,rep(paste0("DHSVM_",i),length(DHSVMvals)))
        AllGaugeIDs = c(AllGaugeIDs,rep(GaugeIDs[gauge],length(DHSVMvals)))
        
      }
    } # End of loop over USGS gauges
  } # End of loop over watersheds
} # End of loop over gauges

StreamflowDataCal = data.frame(Date=AllDates,
                               Streamflow_mmd=AllStreamflowVals,
                               ValueType=AllValueTypes,
                               GaugeID=AllGaugeIDs)

StreamflowDataCal$Date = as.Date(StreamflowDataCal$Date,format="%Y-%m-%d")

################################################################################
# Validation data

ResultsDir = "Val_Results/" # Where the files created by DHSVM are stored
ReferenceDir = "Val_ReferenceData/" # Where the files used as ground-truth are stored

dir = "C:/Users/board/Documents/DHSVM/DHSVM-PNNL-master/Calibrate_MOBOhydro/Validation/"
setwd(dir)

GaugeIDs = c(11413000)
GaugeNames = c("North Yuba River")
CatchmentAreas = c(250) # Areas in mi^2 from USGS

# Read dataframe of streamflow data generated by ProcessStreamflowForDHSVM.R
ReferenceStreamflow = read.csv(paste0(ReferenceDir,"USGS_StreamflowData_Val.csv"))[,-1]
head(ReferenceStreamflow)

# Choose which parameter sets are of interest
VisualizeParameters = c(195,270,276)

AllDates = c()
AllStreamflowVals = c()
AllValueTypes = c()
AllGaugeIDs = c()

# Loop over each parameter set and calculate the objective function value
for (i in VisualizeParameters){
  # Loop over modeled watersheds
  for (bsn in 1:length(BasinNames)){
    # Read the streamflow data output by DHSVM (drop first line that is date-only)
    DHSVMheader = read.table(paste0(ResultsDir,"Val_Params",i,"_",BasinNames[bsn],"/Streamflow.Only"), nrows=1)
    DHSVMstreamflow = read.table(paste0(ResultsDir,"Val_Params",i,"_",BasinNames[bsn],"/Streamflow.Only"), skip=2)
    names(DHSVMstreamflow) = DHSVMheader
    DHSVMstreamflow$DATE = as.Date(DHSVMstreamflow$DATE, format="%m.%d.%Y") # Convert to day only
    
    # Loop over each gauge
    for (gauge in 1:length(GaugeIDs)){
      
      # Only proceed if this gauge is in the current watershed
      if (paste0("Gauge_",GaugeIDs[gauge]) %in% DHSVMheader){
        
        # Reset the vector containing modeled values to be compared with reference data
        DHSVMvals = c()
        # Parse the corresponding reference values into a vector
        ReferenceVals = ReferenceStreamflow[,paste0("Gauge_",GaugeIDs[gauge])]
        
        # Aggregate DHSVM output from m^3/timestep to m^3/s as a daily average for the current gauge
        for (day in 1:length(ReferenceStreamflow$Date)){
          Ptrs = which(DHSVMstreamflow$DATE == ReferenceStreamflow$Date[day])
          DailyQ = sum(DHSVMstreamflow[,paste0("Gauge_",GaugeIDs[gauge])][Ptrs]) / (24*60*60) # m^3/timestep --> m^3/s
          
          # Append to hydrograph for NSE
          DHSVMvals = c(DHSVMvals, DailyQ)
          
        } # End of daily gauge aggregation loop
        
        # Convert m^3/s to mm/d
        DHSVMvals = 1000 * DHSVMvals * (60*60*24) / (CatchmentAreas[gauge] * 2.58999 * 1000^2)
        ReferenceVals = 1000 * ReferenceVals * (60*60*24) / (CatchmentAreas[gauge] * 2.58999 * 1000^2)
        
        if (i==VisualizeParameters[1]){
          AllDates = c(AllDates,ReferenceStreamflow$Date)
          AllStreamflowVals = c(AllStreamflowVals,ReferenceVals)
          AllValueTypes = c(AllValueTypes,rep("Measured",length(ReferenceVals)))
          AllGaugeIDs = c(AllGaugeIDs,rep(GaugeIDs[gauge],length(ReferenceVals)))
        }
        
        AllDates = c(AllDates,ReferenceStreamflow$Date)
        AllStreamflowVals = c(AllStreamflowVals,DHSVMvals)
        AllValueTypes = c(AllValueTypes,rep(paste0("DHSVM_",i),length(DHSVMvals)))
        AllGaugeIDs = c(AllGaugeIDs,rep(GaugeIDs[gauge],length(DHSVMvals)))
        
      }
    } # End of loop over USGS gauges
  } # End of loop over watersheds
} # End of loop over gauges

StreamflowDataVal = data.frame(Date=AllDates,
                               Streamflow_mmd=AllStreamflowVals,
                               ValueType=AllValueTypes,
                               GaugeID=AllGaugeIDs)

StreamflowDataVal$Date = as.Date(StreamflowDataVal$Date,format="%Y-%m-%d")

################################################################################
# Save for TCSI paper figure

StreamflowData = rbind(StreamflowDataCal,
                       StreamflowDataVal)

write.csv(StreamflowData,
          paste0("C:/Users/board/Desktop/DHSVM/ForestPaper/Figures/Cal_Val_Hydrographs/",
                 "Gauge",GaugeIDs[gauge],"_Cal-Val-Ref_Hydrographs.csv"))

library(ggplot2)
ggplot(StreamflowData) +
  geom_line(aes(x=Date,y=Streamflow_mmd,color=as.factor(ValueType)),
            linewidth=1) +
  scale_y_log10() +
  theme_minimal()
